package fr.formation.inti.entities;
// Generated 5 ao�t 2019 16:09:18 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "bd2")
public class Account implements java.io.Serializable {

	private Integer accountId;
	private Employee employee;
	private Float availBalance;
	private Date closeDate;
	private Date lastActivityDate;
	private Date openDate;
	private Float pendingBalance;
	private String status;
	private Integer custId;
	private int openBranchId;
	private String productCd;

	public Account() {
	}

	public Account(Employee employee, Date openDate, int openBranchId, String productCd) {
		this.employee = employee;
		this.openDate = openDate;
		this.openBranchId = openBranchId;
		this.productCd = productCd;
	}

	public Account(Employee employee, Float availBalance, Date closeDate, Date lastActivityDate, Date openDate,
			Float pendingBalance, String status, Integer custId, int openBranchId, String productCd) {
		this.employee = employee;
		this.availBalance = availBalance;
		this.closeDate = closeDate;
		this.lastActivityDate = lastActivityDate;
		this.openDate = openDate;
		this.pendingBalance = pendingBalance;
		this.status = status;
		this.custId = custId;
		this.openBranchId = openBranchId;
		this.productCd = productCd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ACCOUNT_ID", unique = true, nullable = false)
	public Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPEN_EMP_ID", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Column(name = "AVAIL_BALANCE", precision = 12, scale = 0)
	public Float getAvailBalance() {
		return this.availBalance;
	}

	public void setAvailBalance(Float availBalance) {
		this.availBalance = availBalance;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CLOSE_DATE", length = 10)
	public Date getCloseDate() {
		return this.closeDate;
	}

	public void setCloseDate(Date closeDate) {
		this.closeDate = closeDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_ACTIVITY_DATE", length = 10)
	public Date getLastActivityDate() {
		return this.lastActivityDate;
	}

	public void setLastActivityDate(Date lastActivityDate) {
		this.lastActivityDate = lastActivityDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "OPEN_DATE", nullable = false, length = 10)
	public Date getOpenDate() {
		return this.openDate;
	}

	public void setOpenDate(Date openDate) {
		this.openDate = openDate;
	}

	@Column(name = "PENDING_BALANCE", precision = 12, scale = 0)
	public Float getPendingBalance() {
		return this.pendingBalance;
	}

	public void setPendingBalance(Float pendingBalance) {
		this.pendingBalance = pendingBalance;
	}

	@Column(name = "STATUS", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CUST_ID")
	public Integer getCustId() {
		return this.custId;
	}

	public void setCustId(Integer custId) {
		this.custId = custId;
	}

	@Column(name = "OPEN_BRANCH_ID", nullable = false)
	public int getOpenBranchId() {
		return this.openBranchId;
	}

	public void setOpenBranchId(int openBranchId) {
		this.openBranchId = openBranchId;
	}

	@Column(name = "PRODUCT_CD", nullable = false, length = 10)
	public String getProductCd() {
		return this.productCd;
	}

	public void setProductCd(String productCd) {
		this.productCd = productCd;
	}

}
